[package]
name = "corner"
version = "0.4.1"
edition = "2021"
authors = ["Ge Xianliang <lr_kkr@outlook.com>"]

[dependencies]
rocket = "0.5.0-rc.2"
rocket_dyn_templates = { version = "0.1.0-rc.2", features = ["tera"]}
toml = "0.5.9"
serde = "1.0.140"
